language: android
sudo: required
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - ANDROID_API=26
  - EMULATOR_API=21
  - ANDROID_BUILD_TOOLS=26.0.2
  - ADB_INSTALL_TIMEOUT=5
  - secure: ELAzw0XuibOAmfU1IJZvKnGbfmW/Y6O79kFIJQKY+1mCWuMA8fNwVXCsrkvPAnnVRLt3nF++4xMd+bNrH+OLAxiGyBWhdSHE0wuPP5RsJ8oYVivthnDEdM5t8NlgcWAeQ8Myjwbm9HhflGp8t/JqYSqH/SazxijsRgYJYorGNn72IGjSfVByK+OrAblDfcvKGxG0CMuzyP9DvCOEO1fZAPRMXcJLCE1z4p1GhnGSZA4xqL+cnsUb6uwiqnY+UFgnbG/QhXE+k+/1IrB/3gHQ03b7VLWgPUXtl7IG6z7yGWIEvddEu96ogxejuEe9yEahl7OQa5pQgefhiQXkQL+xhZ8UlxZU8iHfhZROOI3wEDW5lu79abXx06RviW822abww0kKIPZs62izEgqsTDa+SCOm3LHe9xraD9JOG9yIfbWPCoqtoORhVShBNfnme557oipMM6hsEgEszcF1IdHTsce54caBAe8SuyvsRHSX6Q1gX6W0GmP0uBK2L3kt1/LOKVqm7hHo1ERw39DjgQWNfI8heVu2KLjElmWROf1V7L6qDIXqFbNljCnk8BPvaI65xLNK20W1q3xIrtOP/hTvCnnL+aBoXwtAF6DoYUYHbXOF2e/4Qfk9usptyKOrx28ljD/DtFBFVQt4JsNc6UQPlj+FFlt732mXFSDIRhblCKk=
  - secure: WCETpAayp5F6EM6JrUpbO0uvi2bV7LtRvlTf8gjf/1bIeAwiEVn10pPOisbkOUn8/hSzg/THBraUnlB+x5z1Hg12a+ErUzYHXaZb4wR0J13wqvbn2JliYVbAB+A1YMKgv/Q9EFhDAWn9ZzdnW37x2NbK7PQ/Goh5/++38hgNCd5I1MYa90XVMUcDKUWiKyqVJqYhMrXxNsFaY8rABIPi79rSMeSuv8pOwPgpUwrsO0fzuOPu9/KD7MK6e8Jp8afFnk5BR6jNrFeDRxs/Dd8gyp1qYSBjbhIB+0AcAmBvUhOzbhtR5nP9EAGKJvxMJJFI+QOjmPSkCURQE7LgIOE0lCMoWf8r21nhxIDroB/nWqn7sdLvrM3mfjYXamephkbvxRym2kjXNbiU3wk38CJTc/BuwCjRWxXz+WIeEJmuVre3v2t1+9F6nkr6jYlYjuZw1ei/UAU3YhStAIz64CuDEjcxxYlOjEB10tLPwOOW2uaEveTFqYWzb3aJ9sWEr/oXKWIPjOmbAHyDVmBqsVkOTTU2u64jw0eOGYGyOdWoV9aKCr18TVR2V94MZhGQwqWe1ef6ZVBFRL9E3NVdOd09TKhVTX+vy82EJoCLt+0ZiBGnoQRng2IInG/fMrTvZ5CvfWXnQUZA7V/8Zl1hJZdZWxkWJftjDlj3GR/B7XxO8pY=
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv
  -in key/XmasTower.jks.enc -out XmasTower.jks -d
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
script:
- "./gradlew android:clean android:generateReleaseSources BaseGameUtils:generateReleaseSources android:assembleRelease -PdisablePreDex --stacktrace"
before_deploy:
- cp $TRAVIS_BUILD_DIR/XmasTower.jks $HOME
- cd android/build/outputs/apk/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/XmasTower.jks
  -storepass $storepass -keypass $keypass android-release-unsigned.apk Noxalus
- jarsigner -verify android-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/26.0.2/zipalign -v 4 android-release-unsigned.apk XmasTower.apk"
deploy:
  provider: releases
  file: XmasTower.apk
  skip_cleanup: true
  on:
    repo: Noxalus/Xmas-Tower
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: h8gUa6wAwwf4nsRBslpwxlkA4zOh2Tuv6Qf8VmSSBBK0UzYMKlGkc/7wIJ1Y/OhH5RsunIGPi6z/qKktLakSG+tEhDcIHd3OjhJAT4Nfx/C1ofDzOGZgHtrCR41rrdb10K2Fp7o52mbJDF9WB/fkexUvkuMGX6TzrvFftBKtNs9FsjYVimaCLxN8czhkOWRkytIK9kk+2zYTdXFI0TM5QuzXUPhe6X3pJGD/gxviYXgtqkN6hwWLHNiFVHO2EQS2FxEY5PXMVAnzgXZBsGBuWFa3CiI6aYkqBj6jKKW3oh53IAg3UXjj1G3afPzZPvAfS+kgHqcyqVbwe5BgVt+hekjm6vDERo5lvM0iia8DfUCQu7QOVT45qHurk+b7ZIO/ivDYkb6kXbVwtUdceHw3oTCA6lulB6qHet++Ie6/UiFa106xc7w2XDqnw0we5Npfz42WQ37trD9gGbQhpUx3rD5xlqrYsCVZBVZ2+4f7fvXDC6/yLh54yLfSRGFC8UN1Y0poKZNO53ZNz8aW+3JOaEX8hG89aoDk9tCTjAdl1KwqQlP7guWQ1DWbYyPYMHsaFPfxgEeuHuOcxXWtR7GQ9IhBsWnJkNjtgvG3uq9Iqtslpme4LVUKL6JGG6rz3NY5mOnwIPug5xWSP/pGnpbE+71z5QTse8g3GOJqTk6tNxo=
